version: "3.6"

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    # volumes:
    #   - ./conf/database:/var/lib/mysql
    #   - ./conf/database/backup.sql.gz:/docker-entrypoint-initdb.d/migrate.sh
    #   - ./conf/database/migrate.sh:/docker-entrypoint-initdb.d/migrate.sh
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./conf/php:/usr/local/etc/php/conf.d/
    entrypoint: ["/usr/local/bin/entrypoint.sh"]

  nginx:
    depends_on:
      - db
    image: nginx
    links:
      - php
    ports:
      - '80:80'
    volumes:
      - ./app:/app
      - ./conf/nginx:/etc/nginx/conf.d
